### ISSUE TITLE
Curso Github - Duvida

### ISSUE THREAD

**Issue by caduguimaraes** [gustavoguanabara/gustavoguanabara.github.io#9]
Olá professor. Como eu faço para dar unfork em outros repositórios do Github. Dei fork em alguns por desconhecimento e queria remover estes repositórios de terceiros. Obrigado. Abs

**Comment by emanoeldelfino** [comment]
Você pode simplesmente deletar o repositório, não existe "unfork". Quando você dá um fork em um projeto você está simplesmente copiando ele para o seu GitHub, para remover essa cópia do seu GitHub basta excluí-la como  faria com qualquer outro projeto seu.

**Comment by caduguimaraes** [comment]
Perfeito. Obrigado @emanoeldelfino  Abs
